import type { Job, JobResource, Scholarship } from "./types";
import { slugify } from "./format";

function scholarship(data: Omit<Scholarship, "id" | "slug" | "isActive" | "region" | "sourceRank"> & { slug?: string; region?: string }) {
  return {
    id: data.slug ?? slugify(data.title),
    slug: data.slug ?? slugify(data.title),
    region: data.region ?? "Europe",
    isActive: true,
    sourceRank: "official",
    ...data
  } satisfies Scholarship;
}

function job(data: Omit<Job, "id" | "slug" | "isActive"> & { slug?: string }) {
  return {
    id: data.slug ?? slugify(data.title),
    slug: data.slug ?? slugify(data.title),
    isActive: true,
    ...data
  } satisfies Job;
}

export const expandedScholarships = [
  scholarship({
    title: "Oxford Clarendon Scholarships",
    provider: "University of Oxford",
    country: "United Kingdom",
    description: "Major graduate scholarships awarded for academic excellence across eligible master's and doctoral courses at Oxford.",
    eligibility: "Excellent academic record, admission to an eligible Oxford graduate course and complete course application by the relevant funding deadline.",
    benefits: "Course fees and a grant for living costs.",
    requiredDocuments: ["Graduate application", "Academic transcripts", "References", "Statement of purpose", "Written work where required"],
    applicationProcess: ["Choose an eligible Oxford graduate course.", "Submit the course application by the December or January funding deadline.", "Eligible applicants are considered automatically."],
    deadline: new Date("2027-01-20T23:59:00.000Z"),
    officialUrl: "https://www.ox.ac.uk/clarendon",
    sourceOrg: "University of Oxford",
    fieldOfStudy: "Multiple fields",
    degreeLevel: "POSTGRADUATE",
    coverageType: "FULL",
    accessTier: "PREMIUM_PLUS",
    isFeatured: true
  }),
  scholarship({
    title: "Cambridge Trust International Scholarships",
    provider: "University of Cambridge",
    country: "United Kingdom",
    description: "Cambridge Trust awards for international students applying to eligible undergraduate and postgraduate programmes.",
    eligibility: "International applicant with strong academic performance and admission to an eligible Cambridge programme.",
    benefits: "Full or partial funding depending on award type and applicant profile.",
    requiredDocuments: ["Course application", "Academic records", "References", "Funding section responses", "English proof where required"],
    applicationProcess: ["Apply through the official Cambridge admissions route.", "Complete the funding section of the application.", "Submit by the course funding deadline."],
    deadline: new Date("2027-01-07T23:59:00.000Z"),
    officialUrl: "https://www.cambridgetrust.org/scholarships",
    sourceOrg: "Cambridge Trust",
    fieldOfStudy: "Multiple fields",
    degreeLevel: "ALL",
    coverageType: "PARTIAL",
    accessTier: "PREMIUM",
    isFeatured: true
  }),
  scholarship({
    title: "Imperial College London President's PhD Scholarships",
    provider: "Imperial College London",
    country: "United Kingdom",
    description: "Competitive PhD funding for outstanding students with strong research potential at Imperial College London.",
    eligibility: "Excellent academic profile, confirmed supervisor fit and application to an eligible Imperial PhD programme.",
    benefits: "Tuition fees, annual stipend and consumables fund.",
    requiredDocuments: ["PhD application", "Research proposal", "Transcripts", "CV", "References"],
    applicationProcess: ["Identify a supervisor and eligible department.", "Submit the PhD application by a scholarship round deadline.", "Departments nominate strongest candidates."],
    deadline: new Date("2027-03-06T23:59:00.000Z"),
    officialUrl: "https://www.imperial.ac.uk/study/fees-and-funding/scholarships-search/presidents-phd-scholarships/",
    sourceOrg: "Imperial College London",
    fieldOfStudy: "Science, engineering, medicine and business",
    degreeLevel: "PHD",
    coverageType: "FULL",
    accessTier: "PREMIUM_PLUS",
    isFeatured: true
  }),
  scholarship({
    title: "Gates Cambridge Scholarship",
    provider: "University of Cambridge",
    country: "United Kingdom",
    description: "Prestigious full-cost postgraduate scholarship for academically outstanding applicants with leadership and social impact potential.",
    eligibility: "Applicant from outside the UK applying to an eligible full-time postgraduate degree at Cambridge.",
    benefits: "University composition fee, maintenance allowance, travel and selected additional discretionary funding.",
    requiredDocuments: ["Graduate application", "Gates statement", "Research proposal where required", "References", "Academic transcripts"],
    applicationProcess: ["Apply through the Cambridge graduate application portal.", "Complete the Gates Cambridge funding section.", "Submit before the international funding deadline."],
    deadline: new Date("2026-12-03T23:59:00.000Z"),
    officialUrl: "https://www.gatescambridge.org/apply/how-to-apply/",
    sourceOrg: "Gates Cambridge",
    fieldOfStudy: "Multiple fields",
    degreeLevel: "POSTGRADUATE",
    coverageType: "FULL",
    accessTier: "PREMIUM_PLUS",
    isFeatured: true
  }),
  scholarship({
    title: "Erasmus Mundus Joint Masters Scholarships",
    provider: "European Commission",
    country: "European Union",
    description: "EU-funded scholarships for selected joint master's programmes delivered by consortia of European universities.",
    eligibility: "Bachelor's degree or equivalent and admission to a participating Erasmus Mundus Joint Masters programme.",
    benefits: "Participation costs, travel contribution and monthly allowance according to programme rules.",
    requiredDocuments: ["Programme application", "Academic transcripts", "CV", "Motivation letter", "References", "Passport"],
    applicationProcess: ["Search the official Erasmus Mundus catalogue.", "Apply directly to selected joint master's programmes.", "Follow each consortium deadline and document list."],
    deadline: new Date("2027-01-31T23:59:00.000Z"),
    officialUrl: "https://erasmus-plus.ec.europa.eu/opportunities/opportunities-for-individuals/students/erasmus-mundus-joint-masters",
    sourceOrg: "European Commission",
    fieldOfStudy: "Multiple fields",
    degreeLevel: "POSTGRADUATE",
    coverageType: "FULL",
    accessTier: "FREE",
    isFeatured: true
  }),
  scholarship({
    title: "France Excellence Eiffel Scholarship Program",
    provider: "Campus France",
    country: "France",
    description: "French government excellence scholarship for master's and doctoral candidates nominated by French higher education institutions.",
    eligibility: "High-potential international applicant nominated by a French institution in an eligible field and degree level.",
    benefits: "Monthly allowance, travel, insurance and related support; tuition rules depend on institution.",
    requiredDocuments: ["Institution nomination file", "CV", "Transcripts", "Study project", "References"],
    applicationProcess: ["Apply to an eligible French institution.", "Request Eiffel consideration from the institution.", "The institution submits nominated files to Campus France."],
    deadline: new Date("2027-01-08T23:59:00.000Z"),
    officialUrl: "https://www.campusfrance.org/en/france-excellence-eiffel-scholarship-program",
    sourceOrg: "Campus France",
    fieldOfStudy: "Engineering, sciences, economics, law, political science and related fields",
    degreeLevel: "POSTGRADUATE",
    coverageType: "FELLOWSHIP",
    accessTier: "PREMIUM",
    isFeatured: false
  }),
  scholarship({
    title: "Orange Tulip Scholarship",
    provider: "Nuffic / Dutch Higher Education Institutions",
    country: "Netherlands",
    description: "Country-specific scholarships offered by Dutch universities for talented international students.",
    eligibility: "Nationality and programme eligibility depend on the participating Dutch institution and local Nuffic rules.",
    benefits: "Partial or full tuition support depending on institution.",
    requiredDocuments: ["Admission application", "Scholarship form", "Academic documents", "Motivation letter", "Passport"],
    applicationProcess: ["Check participating universities and eligible programmes.", "Apply to the university first where required.", "Submit the Orange Tulip Scholarship file by the country deadline."],
    deadline: new Date("2027-04-01T23:59:00.000Z"),
    officialUrl: "https://www.studyinnl.org/finances/orange-tulip-scholarship-programme",
    sourceOrg: "Nuffic",
    fieldOfStudy: "Multiple fields",
    degreeLevel: "ALL",
    coverageType: "PARTIAL",
    accessTier: "FREE",
    isFeatured: false
  }),
  scholarship({
    title: "University of Melbourne Graduate Research Scholarships",
    provider: "University of Melbourne",
    country: "Australia",
    region: "Australia",
    description: "Research training scholarships for high-achieving domestic and international graduate researchers.",
    eligibility: "Application to an eligible graduate research degree with strong academic and research potential.",
    benefits: "Fee offset, living allowance and selected relocation or health cover support.",
    requiredDocuments: ["Research degree application", "Academic transcripts", "Research proposal", "CV", "Supervisor evidence where required"],
    applicationProcess: ["Apply for an eligible graduate research course.", "Complete scholarship consideration requirements.", "Track outcome through the university applicant portal."],
    deadline: new Date("2026-10-31T23:59:00.000Z"),
    officialUrl: "https://scholarships.unimelb.edu.au/awards/graduate-research-scholarships",
    sourceOrg: "University of Melbourne",
    fieldOfStudy: "Research degrees",
    degreeLevel: "PHD",
    coverageType: "FULL",
    accessTier: "PREMIUM",
    isFeatured: true
  }),
  scholarship({
    title: "Fulbright Foreign Student Program",
    provider: "Fulbright Program",
    country: "United States",
    region: "United States",
    description: "U.S. government exchange scholarship for graduate study and research, administered through country-specific Fulbright commissions or U.S. embassies.",
    eligibility: "Citizenship, degree level and field rules vary by country; applicants usually need strong academics, leadership and English readiness.",
    benefits: "Tuition, stipend, health benefits and travel support depending on country programme.",
    requiredDocuments: ["Country application", "Academic transcripts", "Essays", "References", "Test scores where required"],
    applicationProcess: ["Open the official Fulbright country page.", "Confirm local eligibility and deadline.", "Submit through the country-specific application system."],
    deadline: new Date("2027-05-01T23:59:00.000Z"),
    officialUrl: "https://foreign.fulbrightonline.org/",
    sourceOrg: "Fulbright Program",
    fieldOfStudy: "Multiple fields",
    degreeLevel: "POSTGRADUATE",
    coverageType: "FULL",
    accessTier: "FREE",
    isFeatured: true
  }),
  scholarship({
    title: "Khalifa University Graduate Scholarships",
    provider: "Khalifa University",
    country: "United Arab Emirates",
    region: "Middle East",
    description: "Graduate scholarships for master's and doctoral students in engineering, science, computing and related disciplines.",
    eligibility: "Admission to an eligible graduate programme, strong academic record and fulfilment of programme-specific requirements.",
    benefits: "Tuition support, monthly stipend and additional benefits depending on scholarship category.",
    requiredDocuments: ["Graduate application", "Transcripts", "Statement of purpose", "References", "English test where required"],
    applicationProcess: ["Select an eligible graduate programme.", "Submit the official admission application.", "Complete scholarship requirements in the same portal."],
    deadline: new Date("2026-11-15T23:59:00.000Z"),
    officialUrl: "https://www.ku.ac.ae/graduate-scholarships",
    sourceOrg: "Khalifa University",
    fieldOfStudy: "Engineering, science, AI, computing and medicine",
    degreeLevel: "POSTGRADUATE",
    coverageType: "FULL",
    accessTier: "PREMIUM",
    isFeatured: false
  })
];

export const expandedJobs = [
  job({
    title: "Remote Technology and Product Roles",
    organization: "We Work Remotely",
    location: "Remote worldwide",
    country: "Remote",
    description: "Remote-first listings across software engineering, product, design, support, marketing and operations.",
    requirements: "Create a targeted CV and verify each employer's official domain before sending documents.",
    salaryRange: null,
    deadline: null,
    officialUrl: "https://weworkremotely.com/",
    sourceOrg: "We Work Remotely",
    jobType: "FULL_TIME",
    workplaceType: "REMOTE",
    sector: "Remote Technology",
    accessTier: "FREE",
    isFeatured: true
  }),
  job({
    title: "Curated Remote and Flexible Jobs",
    organization: "FlexJobs",
    location: "Remote and hybrid",
    country: "Global",
    description: "Curated remote, hybrid and flexible roles across customer support, administration, tech, writing, education and business services.",
    requirements: "A complete profile, tailored CV and careful review of subscription value before upgrading on any third-party site.",
    salaryRange: null,
    deadline: null,
    officialUrl: "https://www.flexjobs.com/",
    sourceOrg: "FlexJobs",
    jobType: "FULL_TIME",
    workplaceType: "REMOTE",
    sector: "Remote General",
    accessTier: "PREMIUM",
    isFeatured: true
  }),
  job({
    title: "UN International Professional and Field Roles",
    organization: "United Nations Careers",
    location: "Global duty stations",
    country: "Global",
    description: "Official United Nations professional, field service, consultant, internship and temporary vacancies.",
    requirements: "UN Inspira profile, role-specific education and experience, and official application through the UN careers system.",
    salaryRange: null,
    deadline: null,
    officialUrl: "https://careers.un.org/",
    sourceOrg: "United Nations",
    jobType: "FULL_TIME",
    workplaceType: "ONSITE",
    sector: "International Organizations",
    accessTier: "FREE",
    isFeatured: true
  }),
  job({
    title: "World Bank Development Careers",
    organization: "World Bank Group",
    location: "Washington DC and global offices",
    country: "Global",
    description: "Official development roles in operations, economics, climate, data, finance, procurement and country programmes.",
    requirements: "Relevant degree, professional experience, strong analytical writing and application through the official World Bank portal.",
    salaryRange: null,
    deadline: null,
    officialUrl: "https://www.worldbank.org/en/about/careers",
    sourceOrg: "World Bank Group",
    jobType: "FULL_TIME",
    workplaceType: "ONSITE",
    sector: "Development Finance",
    accessTier: "PREMIUM",
    isFeatured: true
  }),
  job({
    title: "UAE Healthcare and Hospital Roles",
    organization: "Mediclinic Middle East",
    location: "Dubai, Abu Dhabi and UAE facilities",
    country: "United Arab Emirates",
    description: "Direct healthcare roles across nursing, allied health, administration, patient services and hospital operations.",
    requirements: "Healthcare qualifications, license readiness where applicable and direct application through the employer portal.",
    salaryRange: null,
    deadline: null,
    officialUrl: "https://careers.mediclinic.com/MiddleEast",
    sourceOrg: "Mediclinic Middle East",
    jobType: "FULL_TIME",
    workplaceType: "ONSITE",
    sector: "Healthcare",
    accessTier: "FREE",
    isFeatured: false
  }),
  job({
    title: "Australia Skilled and Sponsored Job Search",
    organization: "SEEK Australia",
    location: "Australia",
    country: "Australia",
    description: "Large Australian job marketplace covering professional, healthcare, technical, hospitality and skilled roles.",
    requirements: "Target roles that match qualifications and check employer visa sponsorship wording before applying.",
    salaryRange: null,
    deadline: null,
    officialUrl: "https://www.seek.com.au/",
    sourceOrg: "SEEK",
    jobType: "FULL_TIME",
    workplaceType: "ONSITE",
    sector: "General Jobs",
    accessTier: "FREE",
    isFeatured: false
  }),
  job({
    title: "USA Professional Job Search",
    organization: "LinkedIn Jobs",
    location: "United States and remote",
    country: "United States",
    description: "Professional job marketplace with company pages, recruiter search and filters for remote, onsite and hybrid work.",
    requirements: "Optimized profile, role-specific CV and careful screening of work authorization and employer legitimacy.",
    salaryRange: null,
    deadline: null,
    officialUrl: "https://www.linkedin.com/jobs/",
    sourceOrg: "LinkedIn",
    jobType: "FULL_TIME",
    workplaceType: "HYBRID",
    sector: "Professional Services",
    accessTier: "FREE",
    isFeatured: false
  })
];

export const expandedJobResources: JobResource[] = [
  {
    id: "remotive",
    resourceKey: "remotive",
    title: "Remotive",
    organization: "Remotive",
    category: "remote_jobs",
    region: "Global",
    country: "Remote",
    resourceType: "remote_job_board",
    summary: "Remote job board and newsletter focused on tech, SaaS, customer support, marketing and operations.",
    applyUrl: "https://remotive.com/",
    applicationCostType: "free",
    costNotes: "Listings redirect to employers; verify official company domains before submitting documents.",
    isFeatured: false,
    isActive: true,
    sortOrder: 200
  },
  {
    id: "jobspresso",
    resourceKey: "jobspresso",
    title: "Jobspresso",
    organization: "Jobspresso",
    category: "remote_jobs",
    region: "Global",
    country: "Remote",
    resourceType: "remote_job_board",
    summary: "Curated remote roles across technology, marketing, customer support and product teams.",
    applyUrl: "https://jobspresso.co/",
    applicationCostType: "free",
    costNotes: "Use employer links from each listing and keep a record of submitted applications.",
    isFeatured: false,
    isActive: true,
    sortOrder: 210
  },
  {
    id: "himalayas",
    resourceKey: "himalayas",
    title: "Himalayas",
    organization: "Himalayas",
    category: "remote_jobs",
    region: "Global",
    country: "Remote",
    resourceType: "remote_job_board",
    summary: "Remote job board with salary transparency, company profiles and broad international listings.",
    applyUrl: "https://himalayas.app/jobs",
    applicationCostType: "free",
    costNotes: "Check location restrictions and employer requirements before applying.",
    isFeatured: false,
    isActive: true,
    sortOrder: 220
  },
  {
    id: "remote-co",
    resourceKey: "remote-co",
    title: "Remote.co",
    organization: "Remote.co",
    category: "remote_jobs",
    region: "Global",
    country: "Remote",
    resourceType: "remote_job_board",
    summary: "Remote-first job directory with categories across support, sales, writing, development, design and operations.",
    applyUrl: "https://remote.co/remote-jobs/",
    applicationCostType: "free",
    costNotes: "Remote does not always mean worldwide; review country restrictions.",
    isFeatured: false,
    isActive: true,
    sortOrder: 230
  },
  {
    id: "indeed",
    resourceKey: "indeed",
    title: "Indeed",
    organization: "Indeed",
    category: "onsite_jobs",
    region: "Global",
    country: "Global",
    resourceType: "job_marketplace",
    summary: "Large general job marketplace useful for country-specific onsite, hybrid and remote searches.",
    applyUrl: "https://www.indeed.com/",
    applicationCostType: "free",
    costNotes: "Use official employer links where possible and avoid roles requesting payment.",
    isFeatured: false,
    isActive: true,
    sortOrder: 240
  },
  {
    id: "seek-australia",
    resourceKey: "seek-australia",
    title: "SEEK Australia",
    organization: "SEEK",
    category: "onsite_jobs",
    region: "Australia",
    country: "Australia",
    resourceType: "job_marketplace",
    summary: "Major Australian job marketplace for professional, skilled, healthcare, hospitality and technical roles.",
    applyUrl: "https://www.seek.com.au/",
    applicationCostType: "free",
    costNotes: "Search for sponsorship wording and confirm visa conditions before applying.",
    isFeatured: true,
    isActive: true,
    sortOrder: 250
  },
  {
    id: "usa-jobs",
    resourceKey: "usa-jobs",
    title: "USAJOBS",
    organization: "U.S. Office of Personnel Management",
    category: "onsite_jobs",
    region: "United States",
    country: "United States",
    resourceType: "official_government",
    summary: "Official U.S. federal government jobs portal with eligibility, citizenship and work authorization details.",
    applyUrl: "https://www.usajobs.gov/",
    applicationCostType: "free",
    costNotes: "Read eligibility carefully because many roles are limited by citizenship or security clearance.",
    isFeatured: false,
    isActive: true,
    sortOrder: 260
  },
  {
    id: "bayt-uae",
    resourceKey: "bayt-uae",
    title: "Bayt UAE Jobs",
    organization: "Bayt",
    category: "onsite_jobs",
    region: "Middle East",
    country: "United Arab Emirates",
    resourceType: "job_marketplace",
    summary: "Middle East job marketplace with UAE roles across business, hospitality, healthcare, sales and technology.",
    applyUrl: "https://www.bayt.com/en/uae/jobs/",
    applicationCostType: "free",
    costNotes: "Use verified employer pages and reject any recruitment fee requests.",
    isFeatured: false,
    isActive: true,
    sortOrder: 270
  }
];
